### ISSUE TITLE
Terraforming phase: player behavior while trying to build colony

### ISSUE THREAD

**Issue by mirage109** [Igmat/SpaceExpatriateReact#86]
Не дать возможность игроку нажимать, куда не нужно:
 - [x] -  после того, как он правильно выбрал 3 карты мисии или 4 разыне карты и они ушли  в cardsToDrop у него не должно быть возможности еще нажимать на карты на столе. Игрок или строит колонию или нажимает ресет или заканчивает ход
 - [x]  - когда он выбрал первую карту на столе не выбанной мисии - остальные карты этого типа ему не доступны. Доуступные действия: снова нажать на выбранную карту (уберется из масива) или ресет или конечц хода. Так для каждой последующей карты не типа миссии.
 - [x] - если он выбрал больше одной карты миссии - то он не может выбирать карты другого типа

**Comment by angemariya** [comment]
merged into EpicCardsRefactoring branch, which is waiting to be reviewed
